development:
  clients:
    default:
      uri: "<%= ENV['MONGODB_URL'] %>"
      options:
        server_selection_timeout: 5

  options:


test:
  clients:
    default:
      database: mongo_db_testing_project_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
